### ISSUE TITLE
Review use of justfile instead of Makefile

### ISSUE THREAD

**Issue by castedo** [castedo/sshsig#4]
@jelmer You will soon notice the `justfile` rather than `Makefile` usage if you have not already. This has been partly experimental on my part. I've had my eye on a Makefile replacement for a long time and I think `just` is going to be it. But obviously it's the new shiny kid on the block and Makefiles are still the lingua-franca.

Should I continue with my favorite new toy of justfiles or migrate back to old boring Makefiles for the sake of :yawning_face: long-term maintainability? :smile:

**Comment by jelmer** [comment]
Do we need either, since this is a native Python package? I don't mind if it's there though :)

**Comment by castedo** [comment]
OK, cool `justfile` stays.

Even for a single language project, here are two ways I've been finding justfiles to work well:

1) move more logic out of `.gitlab.yml` and`.github/*` vendor specific formats and put into justfile recipies that get called from small and simpler `.gitlab.yml` and `.github/*`. This also helps being able to more easily reproduce key CI steps on a localy machine

2) not all Python tooling is obvious what is the best way to run them. For instance, `mypy` configuration kind of sucks when it comes to mixing strict and non-strict. It's not clear the best way to call `mypy`. Just calling `mypy` and relying on `pyproject.toml` or `mypy.ini` is lacking functionality. But with a `justfile` it was easy for me to work around these limitations by adding the following two lines to justfile recipe:
```
test:
    ...
    mypy --strict sshsig
    cd tests && mypy --ignore-missing-imports .  # cd for separate mypy cache+config
```
and now it's clear and documented how to static type check the sources and tests separately without having horrible performance.
